// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddUserToCallForSpeakers : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207261428133_AddUserToCallForSpeakers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Z227jNhB9L9B/EPTUFljLCYpgN3B2keZSBM0NUbJ9DGhp7BBLkSpJGfa39aGf1F/oUDdLpGxLuWEf+iZT5Nx4ZuZo/O/f/0y+LBPmLUAqKviRvzca+x7wSMSUz4/8TM8+fPS/fP7xh8lZnCy9r9W+fbMPT3J15D9pnR4GgYqeICFqlNBICiVmehSJJCCxCPbH44/B3jgAFOGjLM+b3GVc0wTyH/jzRPAIUp0RdiViYKpcxzdhLtW7JgmolERw5IcpkG8gL25Gf8J0dEo08b1jRglaEgKbDTRr/MmY5dcKUeUZmqZX96sUcrVH/glh7FzIUrFqbsbtf8CqtYBLt1KkIPXqDmaliIvY94L2ucA+WB9rnDFW4BPXB7/63nXGGJkyXJgRpsD30oPDUAsJvwMHSTTEt0RrkNychdyLMhqH6UG/gHwKxvsmIAHhXGii8bIdwy0zL4nSp2R1L8JsmlD9oKPKbLwbuMdbblquZQa7JJ6CiiRNC+WFqFBLBKTvndMlxJfA5/qpjsIVWVYr+Oh7D5wifmtdTtS2Kz9bYOTM4/urvhRz8SDZqyrujPc1WdB5frmWBQ8KpO/dActfqieaFkk1slLgsdh4LkVyJ5ibIvn7x1BkMjJxFFs23RM5B902cRKsc3BrZuZm/J+ObTONqhk19/PeAH71tOlTLc4SQt8hZ+wwJ2QOb5+smzLhWCkR0RwQ3U3qsSM1znjs9UnXwqGOtEdXMqZpymiENh35vzhR2qGiSvaGiqKStOWOR6M9Ow4Nj92SgPxBE4pZV3UQZAVmDZbaiYHZH4JuhE21XFwHfFMQHJ/bIo1HXXIKT63DDbfaRrnVtrF1W1W2q1/PW6+96IpJMFBodc8NoWVU7Krb9r8D+fXVrjlhUJDCijwGG9jj5IqkKSZlg02WK15YUMmTD+FwupgUMoJIdbDG2tpaEzYErBTWW1SNlp5TaaiTJlNiysRJnDjbegC50rQBz+7N"
                       + "VbCsDprn4rBLrR3wW+LWMT1HNxNsPbnHYKFpq4Sc5RNGZEfDPREsS/impr3tdBctbUrret9feouiNsW2XvSX12CdTWmN5QGeVzSy5W616MqZBNYV2pAJHMxYSWxjsRdSi4LwQnh2VbwemOw+9jZAbBKytpT1en9pLkaGwqPkSy2YFUsDfKrZT8ujevX9QdbuI25NdNvpkLJXHhlY2kyXtAK3rVu6MeuFxlxEFyRNyGr9zzStZAfPNG2wVdjqYpqT2gtlaHFNoXs4bHMJFyYOpbC31CCtqYVFISZlO989pXL6e7HF99D1BY1Nbw9XSkNS4C38i50wimmx3nBFOJ2B0vfiG5iJG9KP5w+66g9JpWL2nU+7pnROTSB2fksPHa9sHFTFqEC/zqCKL4iMnoj8KSHLn18+fHqZOGugtFFYH1/rrGtf0nM+Xr+TMc5b4cydwLzsFnvhYfCk5EWS7OnHAGFvNNFY9/RBc4Vtn7Ivm4QgSkEaIBCG/UZpiR3HIT23kvKIpoQ1vXCbbR/km8jW4uw3p5ACN7Dc4GkflVt4Ri3eysVdMRg41XG/mXfPdgaOdooujR1hKvD6Cww/Z/6zcfzTpaB7NPKek6GmyesPpAFjH2d+tC1grzL0cZkY4q3xryJiXtH5WoThlhyiFtLqPRd8JirEWxZVW6wKeAWaIG0gxxJLPYk0vo5AqXwG/JWwLC+3U4gv+E2m00yjy5BM2aoZDJM42/Tnk622zZObnG2o13ABzaSG+dzw3zLK4truc7cpbRJhMrLsnOYutemg81Ut6VrwnoLK8NWF5B6SlKEwdcNDsoDNtu2OYTtik1NK5pIkqpSxPo8/EX5xsvz8H9uOayoXHwAA"; }
        }
    }
}
