// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class TwitterOnUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207270431146_TwitterOnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Zy47bNhTdF+g/CFq1BWI5QREkA0+CdB7FoPPCyJMuA1q69hChSJWkHPvbuugn9Rd6qZclUral8cwgi+5kijz3wfs4uv73738mH1cJ85YgFRX82H89Gvse8EjElC+O/UzPX73zP3748YfJWZysvM/VvjdmH57k6th/0Do9CgIVPUBC1CihkRRKzPUoEklAYhG8GY/fBa/HASCEj1ieN7nLuKYJ5D/w54ngEaQ6I+xKxMBUuY5vwhzVuyYJqJREcOyHKZCvIC9uRn/CbHRKNPG9T4wS1CQENh+o1vi9UcuvBaLIM1RNr6frFHKxx/4JYexcyFKwam7G7X/AurWAS7dSpCD1+g7mJcRF7HtB+1xgH6yPNc4YLfCJ67e/+t51xhiZMVyYE6bA99K3R6EWEn4HDpJoiG+J1iC5OQu5FaU3jtK3/RzyPhi/MQ4JCOdCE42X7ShuqXlJlD4l66kIs1lC9b2OKrXxbmCKt9zUXMsM9iGegookTQvhBVSoJQak753TFcSXwBf6ofbCFVlVK/joe/ecYvzWshyv7RZ+tkTPmceXF30pFuJesicV3Onva7Kki/xyLQ3uFUjfuwOWv1QPNC2SamSlwJdi47kUyZ1gbork77+EIpOR8aPYsWlK5AJ0W8VJsMnBnZmZq/F/OrbVNKLm1NzPSwfwk6dNn2pxlhD6AjljuzkhC3iRZLUET79RE1TPLHdbBn5SSkQ0D8Tu5vilIyXPeOz1KROFQR3lBk3JmKYpoxHqdOz/4jhpj4iqyDREFBWsjTsejV7bfmhY7JYi5C2aUMz2qnMhGzFrsNKOD8z+EHTDbapl4sbh25zg2NyGNBZ14RSWWocbZrWVcqt8Y+uubmBX3Z63XlvR5ZNgIGh1zw3Q0it2tW/b3xH59dVuuGhQkNGKtAZbWOvkiqQpJmWDxZYrXlhQ2JNX4XCamhQYQaQ62GqtbS0JGxFWKOstikZNz6k0lE2TGTFl4iRO"
                       + "nG09ArmStCWe3ZurwrI6aJ6Lwy6ld4Lfgtv49BzNTLDl5RaDFU07EfKvC8KI7Gj0J4JlCd9GFnad7qLDTbSu9/3RW9S4Cdt60R+vwXabaI3lAZZX9LVlbrXo4kwC6wrtkAmcmLGS2I7FXpFaFIQDw7Or4vWIye5jzxOITSLYRtms90dzY2RoeJQ8rRVmxdIAm2rW1bKoXu2PVNOoJlC9+PLB2u5Hbm112/KQ8lkeGVgiTbe13Lar67o+6xXVOURXaBuX1fIfqVrJMh6p2mCtsGXGNCfHF8rQ65qK9zDY5iRumDjUxN5SB2lNUSwqMilpwf4pm8MTii2+h6YvaWw4QrhWGpIi3sK/2AmjmBabDVeE0zkoPRVfwUwMkcY8flBXfwgrFbPvfFo3owtqHLF3FjB0PLR10BajAP00gza+JDJ6IPKnhKx+Pnx4dhicNRDbCtbH1jrr2pf0mI/g72QM9Vxx5k6QDrvFXvEweNJzEJI9vTkIzJrIDMB6pinLhh8MmnXs+rw+bDqDEQ/SBBVh2LuUlti9HAJ1KymPaEpY0wq3cffJIuPZGs5+cwopcBPiWyztI3IHZ6nhrbze54OBkyb3O37/vGnguKno+NhdZgKvv4jhx8ykto6kugR0j2teclrVVHnz0TZgFOXMtHY57EkGUS6rw3hr/MOKMa/oYgNheCqHqBVp9Z4LPhdVxFsaVVusAngFmiAFIZ8ktg0SaXwdgVL5XPozYVleumcQX/CbTKeZRpMhmbF10xkmcXbJz6dtbZ0nNzlzUU9hAqpJDYu64b9llMW13udug9sGYTKy7MLmLrXpxot1jXQteE+g0n11IZlCkjIEUzc8JEvYrtt+H7Y9NjmlZCFJokqMzXn8ieEXJ6sP/wFMlXacIyAAAA=="; }
        }
    }
}
