// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UniqueUrlKeyOnCallForSpeaker : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291111419_UniqueUrlKeyOnCallForSpeaker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1aW2/bNhR+H7D/IOhpG1DLKYqiLZwWWS5DsOaCyO0eC1o6dohSpEpSmf3b9rCftL+wQ90skbIt2UnWh73JvHznwnMOP57kn7/+nnxYJsx7AKmo4Mf+0Wjse8AjEVO+OPYzPX/xxv/w/scfJudxsvQ+V+temnW4k6tj/17r9F0QqOgeEqJGCY2kUGKuR5FIAhKL4OV4/CY4GgeAED5ied7kLuOaJpD/wJ+ngkeQ6oywKxEDU+U4zoQ5qndNElApieDYD1MgX0Fe3oz+gNnojGjieyeMEtQkBDYfqNb4rVHLrwWiyHNUTa+mqxRyscf+KWHsQshSsGouxuW/w6o1gEO3UqQg9eoO5iXEZex7QXtfYG+stzX2GC3wi+vXr3zvOmOMzBgOzAlT4Hvp63ehFhJ+Aw6SaIhvidYgudkLuRWlN96lr/s55G0wfmkcEhDOhSYaD9tR3FLzI1H6jKymIsxmCdWVzngwMMUjbqqtZQa74M5ARZKmheQCKtQSo9H3LugS4o/AF/q+dsEVWVYj+Ol7nzjF4K1lOS7bLvz8Ad1mPp9f9AWVuR9v5rkSh7qxPJXHQhML8UmyR/VKH7m4+VsGKBlzZaDwV+PBJ3JNHugij3lbDQXS9+6A5ZPqnqZFrRlZleFLsfBCiuROMLdy5PNfQpHJyESY2LJoSuQCdFvFSbAuTVsLVq7G/1WqraYRNafmfJ47tR+9oPRJnfOE0OdP2MuELOC/qBTTP6kJqieWuykDT5QSEc0DsZszfOlIyXMee33KRGFQR7lBUzKmacpohDod+784TtohoioyDRFFBWvjjkejI9sPDYvdUoR0ThOK2V7d6UjSzBgsteMDsz4E3XCbapm4dvgmJzg2tyGNRV04haXW5oZZbaXcKt9Yuu02sKtuz1OvrejySTAQtDrnBmjpFbvat+3viPz6aNcUPSg4esXlgw1kfnJF0hSTskHuyxEvLJj96YtwOHtPCowgUh0k"
                       + "vta2loQXEVYoaxZFo6YlA9NkRkyZOI0TZ1mPQK4kbYhn9+SqsKw2mu9is/vScYLfglv79ALNTPDKyy0GK5q2IuSPLsKI7LjoTwXLEr6JLGzb7bwSmlDOZH/c1nOhidma6I/XeAE00RrD/bEcSt9EdCYH+7IT1p4bgFpx/BZcNdgfp83Zm2DtGRdxEljBaydL4GSLVb7sLOyVo0UpPDAxu2p9j2zs3vY0KdikwG2U9Xh/NDdHhqZHyVBbaVYMDbCp5psti+rR/kg1gWwC1YPPH6ztm9i9VVxCMuTiKLcMvBwMz7Dcto1vuD7rFdU5RFdoG5fV8vdUreRXe6o2WCskCzHNnwWXyjws6kdID4NtNuaGiUPK7CV1kNbkzCJhk5IQ7W67OgypWOJ7aPoDjQ07CldKQ1LEW/iNnTKaX0HVgivC6RyUnoqvYFrISOD279zWLQClYvadt29ndEGNI3Z2QQb2FTZ0XmNE14/TeeUPREb3RP6UkOXPh3dTD4Pb0CHd19zuDuneaO0O6UZL9+16VoBOj3OgE+ta0w7NfZoe30nb8amyy+0YHha+vRJhcGfvICS7W3cQmNWBG4D1RF21NSsa1Nva1k45rBuHEQ/SBBVheGMrLfHOdmjjraQ8oilhTStcutIni4xnazh75gxS4CbEN1jaR+QWplbDW3m9ywcDO4tu32Z3f3Fge7HgOXgzzAQefxHD+/QgN7YguwR0t+eeszvZVHn9VB3QenR6mNsc9iiNR5fLYrw1/tEAY17RxRrCsHMOUSvS6jWXfC6qiLc0qpZYBfAKNEH6QE4kXhsk0jgdgVL53yE+E5blpXsG8SW/yXSaaTQZkhlrtUJM4myTn3dX2zpPbnLKph7DBFSTGgZ0w3/NKItrvS/cC24ThMnI8hY2Z6nNbbxY1UjXgvcEKt1XF5IpJClDMHXDQ/IAm3Xb7cO2xyZnlCwkSVSJsd6PPzH84mT5/l9Ol/3gKiMAAA=="; }
        }
    }
}
