// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SurrogateKeyOnUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207260509321_SurrogateKeyOnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1YzW7jNhC+F+g7CDq1h7W8QRHsBvIuUjsugsbxYuXsnmlp7BBLkSpJGfaz9dBH6it0qH9RdmzHTroFerNH5Dc//DifRn//+Zf/cR0zZwVSUcEH7tte33WAhyKifDlwU7148879+OHHH/ybKF47X8p1F2Yd7uRq4D5qnVx5ngofISaqF9NQCiUWuheK2COR8C76/Xfe274HCOEiluP4n1OuaQzZH/w7FDyERKeETUQETBV2fBJkqM49iUElJISBGyRAvoG8nfa+wrw3Ipq4zjWjBCMJgC2ODKv/3oTlVg7R5Q2GpjezTQKZ24E7JIyNhSwcq+ZiXP47bFoGNH2SIgGpN59hUUDcRq7jtfd59sZqW2OPiQJ/cX35i+vcp4yROUPDgjAFrpNcXgVaSPgNOEiiIfpEtAbJzV7IsiiqcZVcHlaQ917/whTEI5wLTTQedidwK8w7ovSIbGYiSOcx1Q86LMPGs4EZnnIzci1T2Ic4AhVKmuTOc6hASySk64zpGqI74Ev9WFVhQtalBX+6zgOnyN/KV6dqTzu/WWHlzM/Xd30nluJBsrM67tbb92qCP0n7BwXyf65bYRpXC4qFeXV2nJ2Th1zFm5jQlybkljLHZAn/9k1ATdKEItnKroRKY2yw1tatyNcHoBt6oZqC4dR+cpHq2ZJiF8SGNHdxG052R7cmVYVfa6mXi2kput4O1fUnJEmw3g0VLixOkEvw8E1wvMzGOYYXqi1qW0VbecK7jiSwnqJrjHRMpZEcTebEMGAYxZ1lBxxW6WnHmdl9ri59udH8zjd3X0k6B2zB1TUdY5oxdpUsY6ii2/PWUWAEIWFEbumlQ8HSmO/qx0/t3ibnTbRtzw9Hb0l7E7b14HC8hlo30RrmIzIv5beVbmns4viedYQ2ZbwOZyxVtLl4EFPzVnAiPbvanqHs4+T2bS9DxKbWtlFq++FoXY4cS49CCls0y01H5FQJWyujyvrKJOtohb2k"
                       + "8l5phqUNftGn949tncadL3EdLNGKRqZpBxulIc4JGvzBhoxivvWCCeF0AUrPxDcwIyjqyvMnv+rlT6mIfefj35wuqSnE3vffY+eNnZNbhA70eSY3viIyfCTyp5isfz59GjsNzpqwdoL956aml6JId+A57QAOOsqjB5OTkOxh42yksAeI7qvr/jHiyCki76l4f+cC08nDfs6osXPS2OagmE2eOYR0BcT3ml8HfewpdFlDmG+FHELTYmrQcs0tX4jyeDGjZkTlEuv0J6AJdjtyLZHmJNT4OASlsnHzC2FpRrU5RLd8muok1ddKQTxnm2a+vve0/2zSasfsT7Mmqc6RAoZJTcOe8l9TyqIq7nH3Qu6CMNQsugZGheM2wi03FdK94AcCFeUbQQLctI4ZxAlDMDXlAVnB7tj217BdMX9EyVKSWBUY9X7zsdozX6s//AMBWVGE3xYAAA=="; }
        }
    }
}
