// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class PuntOnUtc : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207281454515_PuntOnUtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Zy27jNhTdF+g/CFq1BcZygiKYCewZpHkUQSdxEDnTZUBLtEMMRaok5bG/rYt+Un+hl3pZIiVbsp1gFt05fJz74H0c3fz79z+jT6uIOkssJOFs7J4Mhq6DWcBDwhZjN1Hzd+/dTx9//GF0HUYr50tx7lSfg5tMjt0XpeJzz5PBC46QHEQkEFzyuRoEPPJQyL3T4fC9dzL0MEC4gOU4o8eEKRLh9A/485KzAMcqQfSOh5jKfB12/BTVuUcRljEK8Nj1Y4y+YnE7GfyJZ4MrpJDrXFCCQBMf03lPtYYftFpuKRBEXoNqaj1dxzgVO3YvEaU3XOSCZfUwHP8Dr2sLsPQgeIyFWj/ieQ5xG7qOV7/nmRfLa5U7Wgv4xdTZr65zn1CKZhQW5ohK7Drx2bmvuMC/Y4YFUjh8QEphwfRdnFqRe+M8PuvmkA/e8FQ7xEOMcYUUPLaluKHmZyTVFVpPuZ/MIqKeVFCoDW+Dp/DKVc2VSPAuxCssA0HiTHgG5SsBAek6N2SFw8+YLdRL6YU7tCpW4KfrPDEC8VvKsry2Xfj1Ejynf7696BsiUldO5qkSR/Bk/jZHBOQL/iToUX3TKPceLckijT9DgyeJhes8YppuyhcSZ3k/MLL0OTt4I3j0yKmdxen+s88TEein5lsOTZFYYFVXceRtysTW4pGq8X/FqKupRc2Jfp+3zrGjZ3aXrLmOEHmDnDHdHKEFfpNkNQRPvxEdVK8sty0DL6TkAUkDsbl/Pzek5DULnS5lIjOoodyAKQlVJKYkAJ3G7i+Wk3aIKIpMRURWweq4w8HgxPRDxWK7FAG1UohAthfNFQiTXsMrZflAn/exqrhN1kzcOLzNCZbNdUhtURNOZqlxuWJWXSm7yleObusGZtXt+OqlFU0+8XqCFu9cAc29Ylb7uv0NkV8+7YYuexlfLni110KsR3cojiEpK0Q7X3H8jGVfvvP7M+kow/AC2UCoS21LSdCIoEIZ"
                       + "uyAaNM2pkEIzpMvEZRhZxzoEciGpJZ7tlyvCsriof2eX7a8OK/gNuI1Pb8DMCFpeajE2omkrQvoBhCgSDY3+ktMkYm1kYdvtJsZeRWva745eY+9V2NpGd7wKIa+iVZa7YzUx7Cpo035vv7aBN2z3wC6Idw2xWLRxRp4RfGawe1a0G+XHzKJOOZaVsgMTq6lWd8im5muvk0JVCltH2ax3R7Oju29g5wyzliDZUg+bSr5Ys6hc7Y5UEsAqULn49sFa76R2V7AJRZ/Cn1/pWdw1TzDcto0v2D7rFNUpRFNoa5eV8vdULedHe6rWWyto9iFJaf2t1B8G5UdEB4NNNmWHiUWqzCNlkJbkyiBRo5zQ7B5hWgwnO+I6YPqShJrd+GupcJTFm/8XvaQE0mJz4A4xMsdSTflXrMexQMD2n4KWn/BShvQ7H4XOyIJoR+ycYvScC7RPMUMQoI4zxWRLJIIXJH6K0OrnwyeTh8G1Txv3tbh12rg3YH3a2GpvF6yyMNTjaJ8Jw3cy43utVLDHc4cFWqeQ7T1GOwjJHI0dBGaMu3pgvdIIa0Nheg2Sts0uDht9QcRjoYMKUWivUglosBbHexCEBSRGtGqFzS26ZJH2bAln7lzhGDMd4i2WdhG5hVaV8EZe7/JBzzGePSTZPczrOcvLSAlU7xmH589ieJ+BX+u8r0lA8yzsLUeBVZU335U95nzWwHCbw44y5bOJJ8Rb5T/sEPOSLDYQmkozHNQirTxzy+a8iHhDo+KIUQDvsELQ4tGFgLaBAgXbAZYyHfp/QTRJS/cMh7dskqg4UWAyjmZ0XXWGTpxt8tNRZl3n0SQlV/IYJoCaRLOUCfstITQs9b6xG1wbhM7IvAvrt1S6Gy/WJdI9Zx2BcveVhWSKo5gCmJwwHy1xu267fVj32OiKoIVAkcwxNvfhTwi/MFp9/A9QJcUVIyIAAA=="; }
        }
    }
}
