// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddEventDates : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207281400449_AddEventDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1ZW2/bNhR+H7D/IOhpG1DLKYaiLZwWWS5DsOaCyOkeC1o6dohSpEZSqf3b9rCftL+wQ90skbIt2UnQh705vHznwnP5dPLv3/9MPi4T5j2CVFTwY/9oNPY94JGIKV8c+5mev3rrf/zw4w+T8zhZep+rc6/NObzJ1bH/oHX6PghU9AAJUaOERlIoMdejSCQBiUXwejx+GxyNA0AIH7E8b3KXcU0TyP/AP08FjyDVGWFXIgamynXcCXNU75okoFISwbEfpkC+gry8Gf0Js9EZ0cT3ThglqEkIbD5QrfE7o5ZfC0SR56iaXk1XKeRij/1TwtiFkKVg1TyMx/+AVWsBl26lSEHq1R3MS4jL2PeC9r3Avlhfa9wxWuAvrt/86nvXGWNkxnBhTpgC30vfvA+1kPA7cJBEQ3xLtAbJzV3IrSi98T59088h74Lxa+OQgHAuNNH42I7ilpqfiNJnZDUVYTZLqL7XUaU2vg1M8ZWbmmuZwS7EM1CRpGkhvIAKtcSA9L0LuoT4E/CFfqi9cEWW1Qr+9L17TjF+a1mO17YLP39Ez5mfLy/6gsrclTfzXIkdnuwFWT7OUyKKhbiX7Em90xkU1+SRLvIItDS4VyB97w5YvqkeaFpk/sjK0y/FwQspkjvB3DzO97+EIpOReWyx5dCUyAXotoqTYF0otpaPXI3/a0ZbTSNqTs37vHSWPXlu9ylp5wmhL5AztpsTsoAXSVZL8PQbNUH1zHI3ZeCJUiKieSB2d/AvHSl5zmOvT5koDOooN2hKxjRNGY1Qp2P/F8dJO0RURaYhoqhgbdzxaHRk+6FhsVuKkFxpQjHbq/aKlMmswVI7PjDnQ9ANt6mWiWuHb3KCY3Mb0ljUhVNYal1umNVWyq3yjaPbuoFddXu+em1Fl0+CgaDVOzdAS6/Y1b5tf0fk10+7JsxBwZgrZh1soNaTK5KmmJQNql2ueGHBs09fhcO5dFJgBJHqoNS1trUkbERY"
                       + "oaxdFI2almRIkxkxZeI0TpxjPQK5krQhnt2Xq8Kyumh+F5fd7w4n+C24tU8v0MwEW15uMVjRtBUh/wQijMiORn8qWJbwTWRh2+0uzt5E69rvj97i703Y1kZ/vAYlb6I1lvtjdXHsJmjX/mC/bgLv2B6AXRHvFmK16OJMAiv47GAPnGi3yo+dRb1yrChlByZWV63ukU3d154nhZoUto2yXu+P5kb30MAuGWYrQYqlATbVfLFlUb3aH6kmgE2gevHlg7XdSd2u4BKKIYW/vDKwuBueYLltG19wfdYrqnOIrtA2Lqvl76layY/2VG2wVtjsY5rT+ktlPgzqj4geBttsyg0Th1TZR+ogrcmVRaImJaHZPcR0GE5xxPfQ9EcaG3YTrpSGpIi38C92yiimxfrAFeF0DkpPxVcwA1kkYPvPQetPeKVi9p0PQ2d0QY0jdk4x9huVdcwxYxSgn2aOyR+JjB6I/Ckhy58Pn00eBrd53thl8WHzxv0R2/PGjRb3eZC6NLQjaZ8Zw3cy5XuuZHAHdIeFWq+gHTxIOwjJHo4dBGYNvAZgPdMQa01iBo2Stk0vDht+YcSDNEFFGDZYpSW2WIfl3UrKI5oS1rTCZRd9ssh4toazd84gBW5CfIOlfURuIVY1vJXXu3wwcJDnjkl2j/MGTvMKWoLleybw+YsY3mfkt3Hi1yWgexr2ksPApsrrL8sBkz5nZLjNYU8y53OpJ8Zb47/sGPOKLtYQhkxziFqRVp+55HNRRbylUXXEKoBXoAn2eHIisW2QSON2BErlY//PhGV56Z5BfMlvMp1mGk2GZMZWTWeYxNkmPx9mtnWe3OT0Sj2FCagmNTTlhv+WURbXel+4DW4ThMnIsgubt9SmGy9WNdK14D2BSvfVhWQKScoQTN3wkDzCZt12+7DtsckZJQtJElVirO/jnxh+cbL88B+i63SDJyIAAA=="; }
        }
    }
}
