// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCallForSpeakers : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207242219225_InitialCallForSpeakers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7bOBC+L7DvIOi0PdR0gyJoA7lFaseLYOO4qJzueSyNHaIUqSUpw362HvaR9hV2aP1asmO7CYreJGr4zTf/o/++/xt8XCfCW6E2XMmB/6bX9z2UkYq5XA78zC5ev/M/fvj9t+AmTtbe11LuwsnRTWkG/qO16RVjJnrEBEwv4ZFWRi1sL1IJg1ixi37/HXvTZ0gQPmF5XvAlk5YnuH2h16GSEaY2AzFRMQpTnNOXcIvq3UOCJoUIB36YInxDfTvt/Y3z3ggs+N614EBMQhSLM2n13ztafqWQVN4QNbuZbVLcqh34QxBirHSh2DSFSfwv3Owc0NFnrVLUdvMFFwXEbex7bPcea1+srjXuOBb0JO3lW9+7z4SAuaCDBQiDvpdeXoVWafwTJWqwGH8Ga1FLdxe3VhTeuEovT3PIe9a/cA5hIKWyYCnYHeItmndg7Ag2MxVm84TbBxuVtCk2OKMoN5lbneExxBGaSPM0V55DhVZTQvremK8xvkO5tI+VFyawLk/o0fceJKf8rXR1vPa08psVec49/nzVd2qpHrR4UcVdfwesTvBu2lMlWuCUTmUsqL7cGa5tK+9z+RBto0pMs0y8Wk9emr12Ie3lVTGomwDLu0DZLdiBdhFMIE3JZY32UZx4Yd47hq/D8/tDkmOwyOxpExXbShMVJCyx9ZVUE9Mx165WLMzBBXEYJx2xE/xdajrg9nYzqqNQXnTP+eVuL+3EqAVX+3RMZiZUK1uLsWJ3pF0WGGEEAvSehjdUIkvkoab51O19faiJtu/76eg7PakJu/PhdLxGm2miNY7PsLzsGzvmloddnIC1QthOGdbJmdboaufiU2XcFqm0V+XcKtugKKHjq0CnpnIR3yMHrXjs6incGItJntrhP2IoONlbC0xA8gUaO1Pf0K01VPI/vk1Uw9OYWPziK8WcL7lzxNH94dwZdnAbiEmBfZltQK5AR4+g/0hg/er5E/55cK2pfRDs"
                       + "uZO4O0COz+Mzx3FePhSquSJzctovNbO7RR2w5l9AQHHmyxrC/RNIjFzYa9BS5lYuVBkGsrjJqBRpRWmCFigD4VpbvoDI0ucIjdkuWF9BZC4vkjnGt3Ka2TSz18ZgMhebpr0Be1r/djHZ5RxMt4lrXsIEosldEU3lp4yLuOI97mbpIQiXQ0WxEytaMAluuamQ7pU8Eahw3whTlK5VzDBJBYGZqQxhhYe5HffhrseCEYelhsQUGPV991PK3F/ph/8BNP3S0McOAAA="; }
        }
    }
}
