// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SubmissionStatus2 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208020224039_SubmissionStatus2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1b224bNxB9L9B/WOxTWyBaOSgCJ5ATuL4URmMrsJT00aB2KZkN99Il15W+rQ/9pP5Cyb3ytiuuVlKcIm8yL4czw5nhzOz437//mbxbh9h5gilBcXTmnozGrgMjPw5QtDpzM7p8ceq+e/v9d5OrIFw7n6p1L/k6tjMiZ+4jpckbzyP+IwwBGYXIT2MSL+nIj0MPBLH3cjw+9U7GHmQQLsNynMl9FlEUwvwP9udFHPkwoRnAt3EAMSnH2cwsR3XuQAhJAnx45s4SCD7D9GY6+h0uRpeAAtc5xwgwSmYQL3uSNX7NyXLrA9mRV4w0uplvEpgfe+ZeAIyv47Q8mIiL2fLf4EYaYEMf0jiBKd3cw2UJcRO4jifv89SN9TZhD6eC/Yroq59d5y7DGCwwG1gCTKDrJK/ezGicwl9hBFNAYfABUArTiO+FORelNN4kr+wE8tobv+QC8UAUxRRQdtka4QqZ7wGhl2Azj2fZIkS0opldDJyzKxbJpmkGt8FdQuKnKClOLqBmNGXa6DrXaA2D9zBa0cdaBLdgXY2wn67zMUJMeeuzNJF1H371xMTGfx7/6GuU5nKcLnMihoqxvJV9ocWr+GOK9yoVm3NnOFv1PPRkPO59FXfgCa1yZVfO/0hg6jr3EOeT5BElhZMZKS7hoVh4ncbhfYx1l5HPP8ziLPW5asUdi+YgXUEqkzjxGp/U6alyMr65J5lMftQS8fs5tk3v3ZPY2MxVCNDxLfUmBCv4JVzE/C/ElerA51pbYP4IEh4kfbND+Z4QxV/gWT1fEJoCnx7/5BmTS0aOf+49/AP6/EbuISB7DqKMBtn6epYPm/EBbezkoV7WPJ/6rPZ4GpaYns4u+tS4fgud2nIjveqj3kG3urTP039OSOyjnFozNw+GWOAqChyb+KRQGEOcw1QlwxQlGPmMpjP3J03YW46oWBSOKEInGXc8Gp2ochA47haEQbXaaOzSs4ZCwaf34L9DQbdw"
                       + "f+KqL8U0uoQYUuic55bNhUt8EOi2yLQlGCy17nzXyGGr1u9Rim3mYq+uRxBsYa0XcUQBYq9tldQCCvgYXFNNmnz9DFLBionEQmP/bUxqwpMhuYqZcArV27K5kb8JQrxTBUiQj8ydnjYJS7vSK/XuLL1ZzZFJuF5P0ErnBNBSvKq+yPxbyMb0IuqS2ebcbN2bwIB0xR0C6XBohxWHpvCdYun0Xn391zAxtXmsHirZIbkqNKidTVM19YqyaVVe9Vrqq5NbkCQsKhTqreWIMyuKrRcvZv0LqmGB4fnEUFetqa1PYqkJyx2VWXY0o7QsilGwADxOvQhCbZmFa61OavGw+lVWXq7ayH9LIa1QfNbcsQLXyPSasRmyfCvnGCo60ImQ18EBBqkh9buIcRZGbelj126tcCtCaZP2uFIFV8SUJuzxhKKsiCYM22NpVVYRUZvsLUsjrDrXA7Uqu0pw1aA9TlFGFUGKER1h4inKqhqHp1mHFifJVmdlk8WjMdAQTUGChfWZtx3G5MRipIzSjNuj6TbR1xzKWqFkVsVQD57qyp/EUT1qj1SX8kSgevDZKKsYCAxU2bZqYY61TXG7Nh9GfcsannQ9xZA9RlOQE2Ga0R5erSywSX6tHLNH0cplIpw2eXwllMM/PZTR06k+0Uq5pWdEwqPd7lqalC3pMrPSzRzCpKB5Ml5t3pG0MsDfkbTeVLEINUB5teWG8HJqXXq1YFhNAXqriSmztHRLzQZ772O4gvbUcccLqFD2oB7tSfJRlGOft6slyra3rG3c1223ZMA7SlZF2+/tt9QAnokWaNm+uqR+iOqsX8nuJ2Wmvb3FSku9iyWuw2h/QgFPu2cbQmFYKtKf+AKjPLepFtyCCC0hofP4M+TtYuPx6e5dWvXXRkIC/MxbtRZohbggtn5w7flVr6XLKmDodD9dVtETSP1HkP4QgvWPwzunhsG1dEPtyq65G2pnNLkbqpXTvh1OFZDez9RTenUgIevkXhoc"
                       + "vkyL0aHMSu8OGqa3VhbQu4tnEJLamTMITOm26YH1VXTQHErNpOaXYRqmNrQMQ5ObVIZhtTSeDHOPQpzf5sysiDOFjj0AD9SG0STsvZohur5TDmvfYIYEU67kALNAk2sa0isaH1IU+SgBWORCD5NtjJNLtoZTZy5hAiNuci2c2hzZUUSo4RV3sU0Gh2lFsVKF/TUwtHyy3Llj41krTmeZVT+tu7hwXLWx7cUZ4AX+Z0q1i5c4rn7ZlTH2rmfm1iT9M3vLR5C2psnt/UlF9YDlW4uYqULxxu7SxNTaw2Q6wNyH0t7etKW7yXRER0fIUdufRNk0nzR79DZpHSm7NaS0sX2Azqb+LOs3rRY2v4qepQE3dzBx9GhE0kuQzKEJ/wvKXCtBqwaCfziJiqyiAa3W3ETLuPKuCkXVEiULuIUUBMzPnacs6WdJFJv2IWOXN8Z/AjjLE+8FDG6iaUaTjDKWYbjAG1EY3DN3nZ93W8k0T6Z5pY3sgwVGJuKFq2n0S4ZwUNN9bUhaWiC4yy+TW36XlCe5q02NdBdHlkCl+OqXag7DBDMwMo1m4Am207ZdhrLEJpcIrFIQkhKj2c/+ZOoXhOu3/wEh9yJJzTwAAA=="; }
        }
    }
}
