// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialSubmission : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207300145183_InitialSubmission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1bW2/bNhR+H7D/IOhpG1DLKYqiLZwWWS5DsCYuYrd7DGiJdohSl4pUav+2Pewn7S+M1JU3yZRlu+nQN4eX71x4ziHP0cm/f/8zebcOsfMIU4Li6NQ9GY1dB0Z+HKBodepmdPnslfvu7c8/TS6DcO18qtY95+vYzoicug+UJm88j/gPMARkFCI/jUm8pCM/Dj0QxN7z8fiVdzL2IINwGZbjTO6yiKIQ5n+wP8/jyIcJzQC+iQOISTnOZmY5qnMLQkgS4MNTd5ZA8Bmm19PRX3AxugAUuM4ZRoBxMoN42ZOt8WvOllsTZCQvGWt0M98kMCd76p4DjK/itCRMxMVs+Z9wIw2woQ9pnMCUbu7gsoS4DlzHk/d56sZ6m7CHc8F+RfTlC9e5zTAGC8wGlgAT6DrJyzczGqfwDxjBFFAYfACUwjTie2EuRamNN8lLO4W89sbPuUI8EEUxBZQdtsa4wuZ7QOgF2MzjWbYIEa14ZgcD5+yIRbZpmsFtcBeQ+ClKCsoF1IymzBpd5wqtYfAeRiv6UKvgBqyrEfbTdT5GiBlvTUtTWTfxy0emNv7z+KSvUJrrcbrMmRiqxvJU9oUWr+KPKd6rVmzoss1fMsgoM1/pSfzFuPeJ3IJHtMptXmWDwNR17iDOJ8kDSopYM1Iiw32x8CqNw7sY65Ejn7+fxVnqcwuLOxbNQbqCVGZx4jWhqTNg5Wz8iFIym5zUEvHzObZr7z2g2LjOZQjQ8R32OgQr+C0ixfwr4kZ1YLrWHpjfhYS/lX74oXxOiOJvcLueLQhNgU+PQLn1FikDvPEiaezlvl7WXCP6rHaJGJaYrpAu/tRn7hY+teVGftXLrYNvdWmfK/CMkNhHObdmae4Nd+JlFDg293RhMYb7ntlKhilKMPIZT6fub5qyt5CoRBRIFE8IGXc8Gp2oehAk7laEwbTaeOyys4ZDIbb1kL/DQLdIf+KqEXMaXUAMKXTOfJqno+eA+CDQ"
                       + "fZFZSzBYa93pn1HCVqvfoxbb3MXeXI+g2MJbWXpPAWK3TpXjsaSdj8E11bTJ188gFbyYSCI0/t8mpKY8GZKbmAmnML0tmxv9myDEM1WABP3I0unpg7C0K81Qz84ymtUSmZTr9QStbE4ALdWr2ossv4VuTDeirpltwc02vAkCSEfcoZCOgHZYdWgG36mWzujVN34NU1NbxOphkh2aq54GdbBpioheUUWsqo1eS7lxcgOShD0LhfJjOeLMitrj+bNZ//piWGB4PjGUGWtua0rsic5yKGWWkWacljUiChaAPzzPg1BbZhFaK0otEVY/yirKVRv5b+lJK9RitXCswDU6vWJihizvyCWGig10IuRlYYBBakiBzmOchVFbGtW1W6tjilDapD2uVNAUMaUJezyhRimiCcP2WFrRUUTUJnvr0girzvVAraqQElw1aI8jVxVFMHlGR5x4ivGqzuJp3qK9m2QvtPLR4hIZ6JimR4OFN5q3HcYFxSKdjNKM26PpPtLXPcoamuRmxVAPmeqKmCRRPWqPVJe4RKB68MkYq/gwGGiybVW0HGub4XZtPoz5lrUt6XiKIXuMplAlwjSjxz9m+cGlPx70BKbP+6Dc0vMNwN+X3dUrKT/RdWZ1+jmEyQTy9LfavCNr5ZN6R9Z6c8XehAHK6xvXhFcw6+qlhcDqo7u3mZhyOUvHbzbY+7fhCNqTtR0PoELZg3m0p6VHMY59nq6WmtqesrZxX6fdknPuqFkVbb+n35J1PxEr0PJrdUl9EdV5tpJPT8rcdnuPj5bsFktch/H+iAKe6M42hMKwNKQv+ByjPJuoFtyACC0hofP4M+T9SiwX371NqP7ORUiAn3iv0AKtEFfE1k99Pb+gtbT5BAyd7qfNJ3oEqf8A0l9CsP51eOvOMLiWdpxdxTW34+yMJrfjtEq6a4tNBag11PRUYv2ekE1zL1/Yv02Py6G8S29PGWa+Vo7Qu41kEJLaGjIITGn36IH1XbRwHMrM"
                       + "pO6LYRamdlQMQxOf023BwgrI9ELrAXig/oImL+71lb/rA9ywvgRmqDDlRgQwe8/xk0R64eBDiiIfJQCLUuivURvj55qt4dSZC5jAiJt0i6Q2JDty9RpeccdtOjhMj4WVKezvy3zLt7idWxGetOF01gt1at05/HHNxrbJZEAU+J8Z1S5R4rj2ZVct2LudmXtu9O/HLdX8tm7A7Y03RZLO0ppFzEyhuGN36c5pbc4xETA3WLT37Wxp2zGR6Gh1OGpfj6ib5ttcj6YdrdVit06LNrEP0LLTX2T9pNX64XfRjDPg5A6mjh4dNnqljwU04X/+WGglaNVA8O8TEfSlUFavuY6WcRVdFY6qJUoWcAMpCFicO0tZUs2SFDbtQyYub/n+BHCWJ7YLGFxH04wmGWUiw3CBpW/+PDJ30c/biGSeJ9O8oEX2IQJjE/H60DT6PUM4qPm+MiQtLRA85JfJIz9LypPI1aZGuo0jS6BSffVNNYdhghkYmUYz8AjbeduuQ1ljkwsEVikISYnR7Gd/MvMLwvXb/wBcIoIDtToAAA=="; }
        }
    }
}
