// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SlugOnCallForSpeaker : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207310140067_SlugOnCallForSpeaker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1bW2/bNhR+H7D/IOhpG1DLKYqiLZwWWS5DsCYOYrd7DGiJdohSl4lUZv+2Pewn7S+M1JU3yZRlu+nQN4eX71x4ziHP0cm/f/8z+bAOsfMEU4Li6NQ9GY1dB0Z+HKBodepmdPnijfvh/Y8/TC6DcO18rta95OvYzoicuo+UJu88j/iPMARkFCI/jUm8pCM/Dj0QxN7L8fiNdzL2IINwGZbjTO6ziKIQ5n+wP8/jyIcJzQC+iQOISTnOZmY5qnMLQkgS4MNTd5ZA8AWm19PRH3AxugAUuM4ZRoBxMoN42ZOt8VvOllsTZCQvGWt0M98kMCd76p4DjK/itCRMxMVs+e9wIw2wobs0TmBKN/dwWUJcB67jyfs8dWO9TdjDuWC/Ivr6levcZhiDBWYDS4AJdJ3k9bsZjVP4G4xgCigM7gClMI34XphLUWrjXfLaTiFvvfFLrhAPRFFMAWWHrTGusPkREHoBNvN4li1CRCue2cHAOTtikW2aZnAb3AUkfoqSgnIBNaMps0bXuUJrGHyE0Yo+1iq4AetqhP10nU8RYsZb09JU1k388ompjf88PukrlOZ6nC5zJoaqsTyVfaHFq/hTiveqFRu6M5ytehJ9Ne59ErfgCa1yW1fIfyIwdZ17iPNJ8oiSIsaMlIjwUCy8SuPwPsZ6xMjnH2ZxlvrcsuKORXOQriCVWZx4TUjqDFQ5G9+jk8wmJ7VE/HyO7dJ7DyQ2LnMZAnR8R70OwQp+jQgx/wtxozowXWsPzO9Awt9I3/1QPidE8Ve4Vc8WhKbAp0eg3HqLlAHeeJE09vJQL2uuEX1Wu0QMS0xXSBd/6vN2C5/aciO/6uXWwbe6tM8VeEZI7KOcW7M0D4Y78TIKHJt7urAYw33PbCXDFCUY+YynU/cXTdlbSFQiCiSKJ4SMOx6NTlQ9CBJ3K8JgWm08dtlZw6EQ23rI32GgW6Q/cdWIOY0uIIYUOmc+zdPQc0B8EOi+yKwl"
                       + "GKy17rTPKGGr1e9Ri23uYm+uR1Bs4a0sracAsVunyu1Yss7H4Jpq2uTrZ5AKXkwkERr/bxNSU54MyU3MhFOY3pbNjf5NEOKZKkCCfmTp9PRBWNqVZqhnZxnNaolMyvV6glY2J4CW6lXtRZbfQjemG1HXzLbgZhveBAGkI+5QSEdAO6w6NIPvVEtn9Oobv4apqS1i9TDJDs1VT4M62DTFQ6+oHlZVRq+lzDi5AUnCnoVC2bEccWZFzfH8xax/XTEsMDyfGMqLNbc1JfZEZzmUMstIM07L2hAFC8AfnudBqC2zCK0VpZYIqx9lFeWqjfy39KQVarBaOFbgGp1eMTFDlnfkEkPFBjoR8nIwwCA1pEDnMc7CqC2N6tqt1S9FKG3SHlcqZIqY0oQ9nlCbFNGEYXssrdgoImqTvXVphFXneqBW1UcJrhq0xymqiSJIMaIjTDzFWFXn8DTv0N5JstdZ+WRxaQx0RNMjwcL7zNsO43JiUU5Gacbt0XSf6OsOZc1McqtiqIdMdQVMkqgetUeqS1oiUD34bIxVfAgMNNm2qlmOtc1wuzYfxnzLWpZ0PMWQPUZTmBJhmtHjH7P8wNIfC3rC0uc9UG7peefz92R3tUrKR3SdWZ1+DmEygTzdrTbvyFr5hN6Rtd5csTdggPJ6xjXhFcu6WmkhsPrI7m0mptzN0vGbDfb+bTiC9uRsxwOoUPZgHu1p6FGMY5+nq6WitqesbdzXabfkmDtqVkXb7+m3ZNnPxAq0fFpdUl9EdV6t5M+TMpfd3sujJbfFEtdhvD+hgCe2sw2hMCwN6U98jlGePVQLbkCElpDQefwF8r4klnvv3g5Uf9ciJMDPvCdogVaIK2Lrp72eX8xa2nkChk73084TPYHUfwTpTyFY/zy8RWcYXEvbza7imttudkaT225aJe3bSlMBaY0zPZVXvyNkk9zLl/Sv08tyKK/S21CGma2VA/RuFxmEpLaADAJT2jp6YH0TrRqHMjOpy2KY"
                       + "hamdE8PQxGd0W7CwAjK9zHoAHqiPoMmHe33N7/rQNqz/gBkqTLkRAczecfwkkV4wuEtR5KMEYFEK/RVqY/xcszWcOnMBExhxk26R1IZkR45ewyvuuE0Hh+mlsDKF/X2Bb/nmtnPLwbM2nM46oU6tO3c/rtnYNpMMiAL/M6PaJUoc177sqgR7tzNzb43+nbilit/W9be9waZIzlk6s4iZKRR37C5dOK1NOCYC5kaK9v6cLe05JhIdLQ1H7d8RddN8k+vRnKO1VOzWUdEm9gFac/qLrJ+0Wjf8JppuBpzcwdTRo5NGr/CxgCb8Tx8LrQStGgj+XSKCvhTK6jXX0TKuoqvCUbVEyQJuIAUBi3NnKUuqWZLCpn3IxOWt3Z8BzvLEdgGD62ia0SSjTGQYLvBGVAaPzF3083YhmefJNC9kkX2IwNhEvC40jX7NEA5qvq8MSUsLBA/5ZfLIz5LyJHK1qZFu48gSqFRffVPNYZhgBkam0Qw8wXbetutQ1tjkAoFVCkJSYjT72Z/M/IJw/f4/GlrDIZU6AAA="; }
        }
    }
}
