// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class PuntOnUtc2 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207281457128_PuntOnUtc2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1ZW2/bNhR+H7D/IOhpG1DLDYagDZwWXS5DsOaCyO0eC1o6dohSpEZSqf3b9rCftL+wQ90skbIt2UnQh705vHznwnP5dPLv3/9M3i8T5j2CVFTwU//1aOx7wCMRU7449TM9f/XGf//uxx8mF3Gy9D5X547MObzJ1an/oHV6EgQqeoCEqFFCIymUmOtRJJKAxCI4Go/fBK/HASCEj1ieN7nPuKYJ5H/gn2eCR5DqjLBrEQNT5TruhDmqd0MSUCmJ4NQPUyBfQV7djv6E2eicaOJ7HxglqEkIbD5QrfFbo5ZfC0SRF6iaXk1XKeRiT/0zwtilkKVg1TyMx/+AVWsBl+6kSEHq1T3MS4ir2PeC9r3Avlhfa9wxWuAvro9/9b2bjDEyY7gwJ0yB76XHJ6EWEn4HDpJoiO+I1iC5uQu5FaU3TtLjfg55G4yPjEMCwrnQRONjO4pban4kSp+T1VSE2SyhutIZHwam+MRNtbXMYBfcOahI0rSQXECFWmI0+t4lXUL8EfhCP9QuuCbLagV/+t4nTjF4a1mOy7YLv3hEt5mfLy/6ksrcj7fzXIlD3Vi+ylOhiYX4JNmTeqVT7g15pIs87CwNPimQvncPLN9UDzQt0n1kJeeX4uClFMm9YG7y5vtfQpHJyDyy2HJoSuQCdFvFSbCuDltrRq7G/4WiraYRNafmfV46u548p/tkzUVC6AvkjO3mhCzgRZLVEjz9Rk1QPbPcTRn4QSkR0TwQu9v2l46UvOCx16dMFAZ1lBs0JWOapoxGqNOp/4vjpB0iqiLTEFFUsDbueDR6bfuhYbFbipBRaUIx26u2ijzJrMFSOz4w50PQDbeplolrh29ygmNzG9JY1IVTWGpdbpjVVsqt8o2j27qBXXV7vnptRZdPgoGg1Ts3QEuv2NW+bX9H5NdPu2bJQUGTKzodbODTk2uSppiUDX5drnhhQa7PXoXDCXRSYASR6uDRtba1JGxEWKGsXRSN"
                       + "mpYkSJMZMWXiLE6cYz0CuZK0IZ7dl6vCsrpofheX3Y8NJ/gtuLVPL9HMBFtebjFY0bQVIf/uIYzIjkZ/JliW8E1kYdtth6g3oZzN/rgtxt7EbG30x2uQ8CZaY7k/lsOqm4jO5mBfdsLaewNQK5rdgqsWXZxJYIWaHdqBE9tWsbFzpldGFYXrwDTqqsw9cqf72vMkTJOwtlHW6/3R3IgeGswln2wlRbE0wKaaHbYsqlf7I9V0rwlUL758sLb7ptsDXPowpMyXVwaWcsMKLLdtYweuz3pFdQ7RFdrGZbX8PVUr2dCeqg3WClt7THMSf6XMZ0D9ydDDYJs7uWHiUCj7SB2kNZWyKNOkpC+755QOnymO+B6a/khjw2XCldKQFPEW/sXOGM0bRnXgmnA6B6Wn4iuYmSvSrf1HnfUHu1Ix+87nnTO6oMYRO2cWA6cAG0aVMaLrpxlV8kciowcif0rI8ufDx4+HwW0YKe5rbvdIcW+09khxo6V9sOp60A6ffcYI38kg77kywJ3BHRZivYJ18KzsICR7/nUQmDXTGoD1THOqNXMZNC3aNqA4bL6FEQ/SBBVh2FWVlthXHWp3JymPaEpY0wqXUvTJIuPZGs7eOYcUuAnxDZb2EbmFTdXwVl7v8sHAWZ07Cdk9sRs4sCu4CFbvmcDnL2J4n6nexqFel4DugddLzvuaKq8/JwcM85yp4DaHPckoz+WbGG+N/55jzCu6WEMYBs0hakVafeaKz0UV8ZZG1RGrAF6DJtjiyQeJbYNEGrcjUCqf7H8mLMtL9wziK36b6TTTaDIkM7ZqOsMkzjb5+byyrfPkNqdV6ilMQDWpYSm3/LeMsrjW+9JtcJsgTEaWXdi8pTbdeLGqkW4E7wlUuq8uJFNIUoZg6paH5BE267bbh22PTc4pWUiSqBJjfR//xPCLk+W7/wBWnhyI/yEAAA=="; }
        }
    }
}
