// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251453577_InitialUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVYy27jNhTdF+g/CFq1izGdoAgygTyD1I6LoHE8GDnTNS1dO8RQpEpShv1ts+gn9Rd6qbclO5ZjT9ruZIo893V8Lq/+/vaX93EdcWcFSjMpBu5Fr+86IAIZMrEcuIlZvLt2P3748QfvLozWzpdi36XdhyeFHrjPxsQ3hOjgGSKqexELlNRyYXqBjAgNJbns96/JRZ8AQriI5Tje50QYFkH6A38OpQggNgnlExkC1/k6vvFTVOeRRqBjGsDA9WOgX0HdT3t/wLw3ooa6zi1nFD3xgS+OdKv/3rrllgbR5B26ZjazTQyp2YE7pJyPpcoN6/pm3P47bLYWcOmTkjEos/kMixziPnQdsn2ONA+Wx2pnrBf4JMzVL67zmHBO5xwXFpRrcJ346sY3UsFvIEBRA+EnagwoYc9CGkWejZv4qltC3pP+pU0IoUJIQw0Wu+V4w80Hqs2IbmbST+YRM08mKNzG2sAMq1z33KgEDiGOQAeKxZnxDMo3CgnpOmO2hvABxNI8l1mY0HWxgo+u8yQY8re01cray8bvVpg5+/j2ph/kUj4pflbD7Xx7pCL4i7R/0qDenusdo764vD413Wcvchdu30WUfe8K70hvRJfwb1MLRd5QhkpV/M1Ruu0arE2DZtl+H0xNgHVdgZ3KTqb6vaZGNxPShLTk3oWTkn5nUKX7VXMiWXcquhjZ08a8CY1jzHetreUrjp/1tOE7//i+FWUYJNA72lfpbWkJGwWSoPEWTaOnY6ashhs6p5YBwzBqbetQrMLSnpo1haNKfXHQPmeH2z2+VeAGXJXTMYYZoYanEUPp3YE2nmP4AeVU7RCnoeRJJPYJ3Eund/XHOtqu993Rt3plHXbrRXe8Wvuro9WWj4i86Gdb4RaLbRyPNErYpAxpcabRZppc7MTUTApOpGe7WaYohzi5+9j3IWK7qscWNG9eW8TIlrpjVK1oK5Jy9Y1p0VL35pbSeqnyDTX3cmU9PLm0"
                       + "pDbb4jqYohULrcz6G20gyijl/8mHnGG81YYJFWwB2szkV7BTGHaC1w8/5V1f65D/xyegOVsym4iD486xV+69w0uIBsx5hhexoip4puqniK5/Pn0gOQ2uMWTsBfvfDQ5FJO0x4YS54Ij0HLjrn4TUvL+frWrNO3n7Nnj4Zn7kxTwTPfyDzSWGk7n9mtv73sv7LgP5df+V9/q2wnuk/gXLwz89W1YQ9nuWgMBqQAVa7LkXC1mUFyOqe1RsaVR/AoaiHNFbZdiCBgZfB6B1OsF9oTxJqTaH8F5MExMn5lZriOZ8U4/XIy/bT4eXbZ+9aapi+hwhoJvMKupU/JowHpZ+j9t/yH0Qlpq58qNXOMEi3HJTIj1K0REoT98IYhC2b8wgijmC6anw6Qr2+3Y4h9sZ80aMLhWNdI5RnbcfVIn9ovrhHwmJ1G6DFQAA"; }
        }
    }
}
