// <auto-generated />
namespace SpeakerIO.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SubmissionStatus : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208020220086_SubmissionStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1b224bNxB9L9B/WOxTWyBaOSiCJJATuL4URmPLsJT00aB2KZkN99Il15W+rQ/9pP5Cyb1yeVlxtZLiFHmTeTmcGc4MZ2bH//79z+T9OsTOE0wJiqNT92Q0dh0Y+XGAotWpm9Hli9fu+3fffze5DMK186la95KvYzsjcuo+Upq89TziP8IQkFGI/DQm8ZKO/Dj0QBB7L8fj197J2IMMwmVYjjO5zyKKQpj/wf48jyMfJjQD+CYOICblOJuZ5ajOLQghSYAPT91ZAsFnmF5PR7/DxegCUOA6ZxgBRskM4mVPssZvOFlufSA78pKRRjfzTQLzY0/dc4DxVZyWBxNxMVv+G9y0BtjQXRonMKWbe7gsIa4D1/Ha+zx5Y71N2MOpYL8i+upn17nNMAYLzAaWABPoOsmrtzMap/BXGMEUUBjcAUphGvG9MOeilMbb5JWdQN5445dcIB6IopgCyi5bIVwi8wMg9AJs5vEsW4SIVjSzi4FzdsUi2TTN4Da4C0j8FCXFyQXUjKZMG13nCq1h8AFGK/pYi+AGrKsR9tN1PkaIKW99liKy7sMvn5jY+M/jH32F0lyO02VOxFAxlreyL7R4FX9M8V6lYnPuDGernoeejMe9r+IWPKFVruzS+R8JTF3nHuJ8kjyipHAyI8klPBQLr9I4vI+x6jLy+YdZnKU+V624Y9EcpCtI2yROvMYndXqqnIxv7qlNJj9qifj9HNum9+5JbGzmMgTo+JZ6HYIV/BIuYv4X4kp14HOtLTB/BAkPkr7ZYfueEMVf4Fk9WxCaAp8e/+R7+Af0uWTuISB7Dma0hmF8xcoHRvuQNfr6UC9rnjF1VnnENEt0T1gXfXJ8vYVOZbmWXvlx7aBbXtrnCT4jJPZRTq2emwfNm3wZBY5NnFAojCbeYKqSYYoSjHxG06n7kyLsLUdULApHFCFMG3c8Gp3IchA47haERrVMNHbpWUOh4Ft78N+hoFu4P3Fljz2N"
                       + "LiCGFDpnuWVz4RIfBKotMm0JBkutO+/UcmjU+j1K0WQu9up6BMEW1noeRxQg9upVySWggI/BNVWkydfPIBWsmLRYaOzfxKQivDYkVzEdTqF6WzY38tdBiHcqAQnyaXOnpi/C0q40R747S29Wc6QTrtcTtNI5AbQUr6wvbf4tZKN7EVXJbHNutu5NYKB1xR0C6XBohxWHovCdYun0Xn391zAxmTxWD5XskFwVGtTOpqleekX5sipzeoY65+QGJAmLCoW6ZznizIqi5/mLWf/CZlhgeD7R1DdrauuTWIrAcjhplh3NKC2LUxQsAI9Tz4NQWWbhWquTDB5WvcrKy1Ub+e9WSCsUgRV3LME1Mr1ibIYs78k5hpIOdCLk9WiAQapJwc5jnIWRKY3r2q0UUEUoZdIet1VJFTFbE/Z4QnFURBOG7bGUaqeIqEz2lqUWVp7rgVqVP1tw1aA9TlHOFEGKERVh4knKKhuHp1iHEie1rc7KJotHY6Ah6oIEC+vTbzuMyYlFwTZKM26PptpEX3Moa3YtsyqGevBUV+BaHNWj9kh1SU0EqgefjbKKgcBAlTVV7XKsbYrbtfkw6lvW0lrXUwzZYzSFMRGmGbVHUgpdIqAyeXz1aQduahCiJkJ94oxyS89Ygsep3VWwVp6jysxKq3IInWrlaXS1eUfSytB8R9J6U8ViywDldZJrwguhddHUgmE5eO+tJrqc0NKhNBvs/YbmCsxJ344XUKHsQT3M6e1RlGOft6ukuLa3rGzc120bctcdJSuj7ff2Ddn7M9ECJU+Xl9QPUZ2vS3n5pMyRtzcpKUlzscR1GO1PKOAJ82xDKAxLRfoTn2OUZyXVghsQoSUkdB5/hrzhiuX0u/c51d/rCAnwM292WqAV4oLY+smy5/c4Q59SwNDpfvqUoieQ+o8g/SEE6x+H9x4NgzP0E+3Krr6faGe0dj+RkdO+PUIVkNoR1FN6dSDR1sm9tAh8mSadQ5mV2l8zTG+tLKB3"
                       + "H8wgJLm3ZRCY1K/SA+ur6EE5lJq12keGaZjcEjIMzdDmMcylCbG5yQFZEacL93oAHqjpoUmye7UedH0VHNYswZQfplwxAWbBIdcOpFYh7lIU+SgBWORCDW1tDIpLtoaTZy5gAiNuJgZObY7sSPxreMnEt8ngMI0fVqqwv3YBwwfCnfsjnrXidBY11dO6CwLHVRvbzpcBXuB/plS7eInj6pdd6WHveqZvBFI/ahs+OZhaFLd3AxUZP8uRFjFTheKN3aVlyNgxpDtA3/Vhbiba0kukO6Kj/+KozUaibJoPiD06iZT+j93aP0xsH6CPqD/L6k3LxcivokNowM0dTBw92n7UsiFzaMJ/QDLXStCqgeAfO6Iiq2hAqzXX0TKuvKtEUbVEygJuIAUB83NnKUvUWeLDpn3I2OVt6J8AzvJkeQGD62ia0SSjjGUYLvBGFAb3zF3n571NbZon07w6RvbBAiMT8WLTNPolQzio6b7SJC0GCO7yy4SU3yXlielqUyPdxpElUCm++qWawzDBDIxMoxl4gmbatsuwLbHJBQKrFISkxGj2sz+Z+gXh+t1/IAKOKMM7AAA="; }
        }
    }
}
